core/blog/api/v1/urls.py
from . import views
from rest_framework.routers import SimpleRouter

app_name = "api-v1"

router = SimpleRouter()
router.register("post", views.PostModelViewSet, basename="post")
router.register("category", views.CategoryModelViewSet, basename="category")
urlpatterns = router.urls


"""urlpatterns = [
    # path('post/', views.postList, name="post-list"),
    # path('post/<int:id>/', views.postDetail, name="post-detail"),
    # path('post/', views.PostList.as_view(), name="post-list"),
    # path('post/<int:pk>/', views.PostDetail.as_view(), name="post-detail"),
    path('post/', views.PostViewSet.as_view({'get':'list','post':'create'}),name='post-list'),
    path('post/<int:pk>/', views.PostViewSet.as_view({'get':'retrieve','put':'update','patch':'partial_update','delete':'destroy'}), name="post-detail"),
]"""

core/blog/urls.py
from django.urls import path, include
from . import views


app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("post", views.PostListView.as_view(), name="post-list"),
    path("post/api/", views.PostListApiView.as_view(), name="post-list-api"),
    path("post/<int:pk>/", views.PostDetailView.as_view(), name="post-detail"),
    path("post/create/", views.PostCreateView.as_view(), name="post-create"),
    path("post/<int:pk>/edit/", views.PostEditView.as_view(), name="post-edit"),
    path(
        "post/<int:pk>/delete/",
        views.PostDeleteView.as_view(),
        name="post-delete",
    ),
    path("api/v1/", include("blog.api.v1.urls")),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


schema_view = get_schema_view(
    openapi.Info(
        title="Blog Api",
        default_version="v1",
        description="This is a test API for django learning",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="mreiliya333@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api-auth/", include("rest_framework.urls")),
    path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),
    path(
        "swagger/output.json",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]
# serving static and media development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/blog/models.py
from django.db import models
from django.urls import reverse

# getting user model object
# User = get_user_model()


class Post(models.Model):
    """
    this is a to define posts for blog app
    """

    author = models.ForeignKey("accounts.Profile", on_delete=models.CASCADE)
    image = models.ImageField(null=True, blank=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    status = models.BooleanField()
    category = models.ForeignKey("Category", on_delete=models.SET_NULL, null=True)

    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField()

    def __str__(self):
        return self.title

    def get_snippet(self):
        return self.content[0:5]

    def get_absolute_api_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name

core/blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ["title", "content", "status", "category", "published_date"]

core/blog/api/v1/views.py
from rest_framework.permissions import (
    IsAuthenticated
)
from .serializers import PostSerializers, CategorySerializer
from ...models import Post, Category
from rest_framework import viewsets

from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import SearchFilter, OrderingFilter
from .paginations import DefaultPagination


# viewset example for cbv
class PostModelViewSet(viewsets.ModelViewSet):
    #permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]
    serializer_class = PostSerializers
    queryset = Post.objects.filter(status=True)
    filter_backends = [DjangoFilterBackend, SearchFilter, OrderingFilter]
    filterset_fields = ["category", "author", "status"]
    search_fields = ["=title"]
    ordering_fields = ["published_date"]
    pagination_class = DefaultPagination


class CategoryModelViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticated]
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

core/blog/views.py
from django.views.generic.base import TemplateView
from .models import Post
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .forms import PostForm
from django.contrib.auth.mixins import LoginRequiredMixin


class IndexView(TemplateView):
    """
    a class base view to show the index page
    """

    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["name"] = "Abdo"
        context["posts"] = Post.objects.all()
        return context


class PostListView(LoginRequiredMixin, ListView):
    # queryset = Post.objects.all()
    model = Post
    context_object_name = "posts"
    paginate_by = 3
    ordering = "id"

    # def get_queryset(self):
    # posts = Post.objects.filter(status=True)
    # return posts


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post



class PostListApiView(TemplateView):
    template_name = 'blog/post_list_api.html'




class PostCreateView(CreateView):
    model = Post
    # fields = ['author','title','content','status','category','published_date']
    form_class = PostForm
    success_url = "/blog/post"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostEditView(UpdateView):
    model = Post
    form_class = PostForm
    success_url = "/blog/post"


class PostDeleteView(DeleteView):
    model = Post
    success_url = "/blog/post"

core/templates/blog/post_confirm_delete.html
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

core/templates/blog/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>{{object.title}}</h1>
    <hr>
    <small>{{object.author}} - {{author.published_date}}</small>
    <p>{{object.content}}</p>
</body>
</html>

core/templates/blog/post_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Post</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html>

core/templates/blog/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Blog Posts</h1>
    {% for post in posts %}
    <div>
        <a href="{% url 'blog:post-detail' pk=post.id %}"><h2>{{post.id}} - {{post.title}}</h2></a>
        <a href="{% url 'blog:post-edit' pk=post.id %}">
            <h5>Edit</h5>
        </a>
        <a href="{% url 'blog:post-delete' pk=post.id %}"><h5>Delete</h5></a>
        <small>{{post.author.first_name}} {{post.author.last_name}} - {{post.published_date}}</small>
    </div>
    {% endfor %}


    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
</body>
</html>

core/templates/blog/post_list_api.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Blog Posts</h1>
    <ol id="post-wrapper">

        <!--<div>
            <a href="">
                <h2></h2>
        </div>-->
    </ol>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"
        integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $.get('/blog/api/v1/post/',  // url
            function (data, textStatus, jqXHR) { 
                wrapper = $('#post-wrapper');
                for (post of data.results){
                    wrapper.append(`<li><a href="${post.absolute_url}"><h2>${post.title}</h2></a></li>`)
                }
                
                //alert('status: ' + textStatus + ', data:' + data);
                //console.log(data);

            });
    </script>



</body>

</html>